### ISSUE TITLE
Chinese proofreading

### ISSUE THREAD

**Issue by thewchan** [standardebooks/sun-tzu_the-art-of-war_lionel-giles#14]
皆以新書 <- missing 從事, 違教者貧敗 -> 違教者負敗, 意自於新書 -> 意曹自於新書

**Comment by acabal** [comment]
You don't have to open an issue for all of these; one pull request with something like 'fix typos' is enough, and faster for everyone :)

**Comment by thewchan** [comment]
Oh gotcha... Sorry I'm not sure what the workflow should be. I'll just keep working on my end and have one big pull requests when I'm done? How about that? It'll probably take awhile?

**Comment by acabal** [comment]
That's fine!
