### ISSUE TITLE
Dedication page does not appear to be center positioned on Kindle (paperwhite via azw3); likely a margin issue

### ISSUE THREAD

**Issue by thewchan** [standardebooks/sun-tzu_the-art-of-war_lionel-giles#2]

**Comment by acabal** [comment]
If the raw source from Github appears centered in your browser, then the most likely culprit is you forced text-align in your reader settings, which are overriding text-align: center on the dedication. If it doesn't appear right in Github, then some CSS is missing and maybe you could take a look at that to fix it.

**Comment by acabal** [comment]
CSS looks good so this is likely a reader setting issue. If not then you can reopen this. Thanks!
